- name: Create resource group
  azure.azcollection.azure_rm_resourcegroup:
    name: "{{ resource_group }}"
    location: "{{ location }}"

- name: Create virtual network
  azure.azcollection.azure_rm_virtualnetwork:
    resource_group: "{{ resource_group }}"
    name: "{{ vnet_name }}"
    address_prefixes: "{{ address_prefix }}"
    location: "{{ location }}"

- name: Create subnet
  azure.azcollection.azure_rm_subnet:
    resource_group: "{{ resource_group }}"
    name: "{{ subnet_name }}"
    address_prefix: "{{ subnet_prefix }}"
    virtual_network: "{{ vnet_name }}"
